config/routes.rb
Rails.application.routes.draw do
	resources :alumns, controller: 'reader'
	resources :parents

	get '/reader/index'
	root 'reader#index'

end

app/models/alumn.rb
class Alumn < ApplicationRecord

  def self.search(search)
    where("bar_code LIKE ?", "%#{search}%") 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/frequency.rb
class Frequency < ApplicationRecord
end

app/models/parent.rb
class Parent < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/reader_controller.rb
class ReaderController < ApplicationController
	def index
		bar_code = params[:bar_code]

		time = mountCurrentTime()	
		# do method to get date	

		if bar_code != nil && bar_code != ""
			@alumn = Alumn.find_by_bar_code bar_code
			Frequency.create(:bar_code => bar_code.to_s , :date => time.to_s)	
			
		else
			# nothing to do in here
		end

	end
	
	TWO_POINTS = ":"
	DATE_SPACE = "/"
	SPACE_TRACE_SPACE = " - "

	private 
	def mountCurrentTime() 
	
 		hour = Time.current.hour.to_s
 		minute = Time.current.min .to_s
 		day = Time.current.day.to_s
 		month = Time.current.month.to_s
 		year = Time.current.year.to_s

 		correctDate = day + DATE_SPACE + month + DATE_SPACE + year + SPACE_TRACE_SPACE + 
 						+ hour + TWO_POINTS + minute
		return correctDate.to_s
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EscolaXLeitor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reader/index.html.erb
<!-- Field of barcode to look for alumn -->
<form>
  <div class="form-group" style="width:15%; margin:0 auto;" >
    <%= form_tag(alumns_path, :method => 'get' ) do %>
        <%= text_field_tag :bar_code, params[:bar_code] , placeholder: "Código de barras" , value: "" , autofocus: "True"%>
    <% end %>

  </div>
</form>

<% if @alumn != nil%>
	<div class="container">
		<br>
		<center>
			<%= ("<img id =  'profile-image' width = '600' height = '550' alt='image' class= 'list_image' src='data:image/jpg;base64,%s'>" % Base64.encode64(@alumn.image)).html_safe %><br>
	  	</center>
  	</div>
  	<div>
  		<center>
  			<h3> <%= @alumn.name %> </h3>
  		</center>
  	</div>
<% end %>

    
  